import axios from 'axios';
import crypto from 'crypto';
import { config } from '../config/env.js';

/**
 * AI Service Layer
 * Connects Express backend with the FastAPI AI Microservice using Axios.
 * Handles timeouts, retries, data mapping (camelCase -> snake_case),
 * metric normalization, and operational logging.
 */
export class AiService {
  constructor() {
    this.baseUrl = (process.env.AI_SERVICE_URL || config.aiServiceUrl || 'http://localhost:8000').replace(/\/+$/, '');
    this.timeout = 5000; // 5000ms timeout per Step 6

    // Configure dedicated Axios instance
    this.client = axios.create({
      baseURL: this.baseUrl,
      timeout: this.timeout,
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
    });
  }

  /**
   * Step 5: Data Mapping
   * Converts frontend camelCase payload into snake_case expected by FastAPI.
   * Also ensures compatibility with both Phase 11 multi-feature and Phase 12 queue models.
   *
   * @param {Object} input - Raw input from request body
   * @returns {Object} snake_case payload
   */
  mapInputToFastApi(input) {
    const apps7 = Number(input.applicationsLast7Days ?? input.applications_last_7_days ?? 0);
    const apps30 = Number(input.applicationsLast30Days ?? input.applications_last_30_days ?? 0);
    const pending = Number(input.pendingApplications ?? input.pending_applications ?? input.pending_bookings ?? 0);
    const workers = Number(input.availableWorkers ?? input.available_workers ?? 0);
    const avgTime = Number(input.averageCompletionTime ?? input.avg_completion_time ?? 3.5);
    const district = String(input.district || 'Pune').trim();
    const serviceType = String(input.serviceType || input.service_type || 'General').trim();

    return {
      district,
      service_type: serviceType,
      applications_last_7_days: apps7,
      applications_last_30_days: apps30,
      pending_applications: pending,
      expiring_requests: Number(input.expiringRequests ?? Math.round(pending * 0.15)),
      number_of_workers: Number(input.numberOfWorkers ?? Math.max(workers * 2, 20)),
      available_workers: workers,
      average_completion_time: avgTime,

      // Aliases for Phase 12 XGBoost regressor
      pending_bookings: pending,
      avg_completion_time: avgTime,
      day_of_week: input.dayOfWeek || input.day_of_week || ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][new Date().getDay()],
    };
  }

  /**
   * Generates actionable recommendations based on workload strain
   * (Generated by Express, not hardcoded on the frontend - Step 10)
   */
  generateRecommendation(workloadLevel, district, serviceType) {
    switch (workloadLevel.toUpperCase()) {
      case 'CRITICAL':
        return `Critical workload alert: Capacity deficit in ${district} for ${serviceType}. Activate emergency cooperative standby roster immediately.`;
      case 'HIGH':
        return `High demand expected in ${district}. Increase worker availability and re-route members from adjacent zones.`;
      case 'MODERATE':
        return `Balanced operations in ${district}. Standard fair-rotation dispatch recommended.`;
      case 'LOW':
      default:
        return `Surplus capacity available in ${district} for ${serviceType}. Ready for promotional booking allocations.`;
    }
  }

  /**
   * Step 1 & 6: Execute HTTP call with 5000ms timeout and 1 retry on network failure
   *
   * @param {Object} data - Clean input data
   * @returns {Promise<Object>} Normalized prediction result
   */
  async predictWorkload(data) {
    const requestId = crypto.randomUUID ? crypto.randomUUID() : `req-${Date.now()}`;
    const payload = this.mapInputToFastApi(data);
    const startTime = Date.now();

    const makeRequest = async () => {
      return await this.client.post('/predict/workload', payload);
    };

    let response;
    try {
      // First attempt
      response = await makeRequest();
    } catch (firstError) {
      // Do not retry 4xx validation errors (Step 6)
      if (firstError.response && firstError.response.status >= 400 && firstError.response.status < 500) {
        const errorMsg = firstError.response.data?.detail || firstError.message;
        console.error(`[AI Service] [${requestId}] Client validation error: ${JSON.stringify(errorMsg)}`);
        throw new Error(`AI service validation error: ${JSON.stringify(errorMsg)}`);
      }

      console.warn(`[AI Service] [${requestId}] First attempt failed (${firstError.message}). Retrying once...`);

      try {
        // Step 6: Retry once for temporary network/server failures
        response = await makeRequest();
      } catch (retryError) {
        const duration = Date.now() - startTime;
        console.error(`[AI Service] [${requestId}] AI request failed after retry (${duration}ms): ${retryError.message}`);
        
        // Throw meaningful error (Step 1)
        const error = new Error('AI service unavailable');
        error.isAiServiceError = true;
        error.originalError = retryError.message;
        throw error;
      }
    }

    const duration = Date.now() - startTime;
    console.log(`[AI Service] [${requestId}] Prediction succeeded in ${duration}ms (status: ${response.status})`);

    // Step 1: Return normalized responses
    const raw = response.data;
    const rawDemand = Number(raw.predictedDemand ?? raw.predicted_demand ?? 0);
    const rawInspections = Number(raw.predictedInspections ?? raw.predicted_inspections ?? Math.round(rawDemand * 0.22));

    // Calculate workload level if not directly provided
    let level = raw.workloadLevel || raw.workload_level;
    if (!level) {
      const activeWorkers = Math.max(payload.available_workers, 1);
      const strain = rawDemand / activeWorkers;
      if (strain >= 2.0) level = 'HIGH';
      else if (strain >= 1.0) level = 'MODERATE';
      else level = 'LOW';
    }

    // Calculate priority score if not directly provided
    let priority = Number(raw.priorityScore ?? raw.priority_score);
    if (isNaN(priority) || priority === 0) {
      const activeWorkers = Math.max(payload.available_workers, 1);
      const strain = rawDemand / activeWorkers;
      priority = Math.min(100, Math.max(10, Math.round((strain / 2.0) * 50 + (payload.pending_applications / 40) * 35 + 15)));
    }

    const workloadLevel = String(level).toUpperCase();
    const priorityScore = Math.round(priority);
    const recommendation = this.generateRecommendation(workloadLevel, payload.district, payload.service_type);

    return {
      predictedDemand: Math.round(rawDemand),
      predictedInspections: Math.round(rawInspections),
      workloadLevel,
      priorityScore,
      recommendation,
      requestId,
      responseTimeMs: duration,
    };
  }

  /**
   * Step 7: Health Check Helper
   * Calls GET FastAPI /health
   *
   * @returns {Promise<{ success: boolean, aiService: 'online' | 'offline' }>}
   */
  async getAIHealth() {
    try {
      const response = await this.client.get('/health', { timeout: 3000 });
      if (response.status === 200) {
        return { success: true, aiService: 'online', details: response.data };
      }
      return { success: false, aiService: 'offline' };
    } catch (err) {
      return { success: false, aiService: 'offline', error: err.message };
    }
  }
}

export const aiService = new AiService();
export default aiService;

