import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createServer } from 'node:http';
import mongoose from 'mongoose';
import { io as client } from '../../client/node_modules/socket.io-client/build/esm/index.js';
import app from '../src/app.js';
import { initializeNotifications } from '../src/realtime/notifications.js';
import { Notification } from '../src/models/Notification.model.js';
import { User } from '../src/models/User.model.js';
import { Worker } from '../src/models/Worker.model.js';
import { Cooperative } from '../src/models/Cooperative.model.js';
import { Booking } from '../src/models/Booking.model.js';
import { Payment } from '../src/models/Payment.model.js';
import { AuthService } from '../src/services/auth.service.js';
import { BookingService } from '../src/services/booking.service.js';
import { AdminService } from '../src/services/admin.service.js';
import { CooperativeService } from '../src/services/cooperative.service.js';
import { issueWorkOtp, verifyWorkOtp } from '../src/services/bookingVerification.service.js';
import { notify, safelyNotify, bookingNotification } from '../src/services/notification.service.js';
import { scanNotificationReminders } from '../src/services/notificationMonitor.service.js';

// Always use a fresh isolated database, never the application's database.
const dbName = `shramsetu_notifications_test_${Date.now()}`;
await mongoose.connect(process.env.NOTIFICATION_TEST_MONGO_URI || 'mongodb://127.0.0.1:27028', { dbName, serverSelectionTimeoutMS: 5000 });
const http = createServer(app);
const io = initializeNotifications(http);
const sockets = [];
let passed = 0;
const check = (condition, label) => { assert.ok(condition, label); passed++; console.log(`PASS: ${label}`); };
try {
  await Notification.init();
  const users = await User.create(['USER', 'WORKER', 'COOPERATIVE', 'ADMIN', 'USER'].map((role, index) => ({ name: `Test ${index}`, phone: `990000000${index}`, password: 'test-password', role })));
  const [customer, workerUser, manager, admin, stranger] = users;
  const coop = await Cooperative.create({ name: 'Test Guild', registrationDetails: { registrationNumber: 'TEST-001', state: 'Test' } });
  manager.cooperativeId = coop._id; await manager.save();
  const worker = await Worker.create({ user: workerUser._id, cooperative: coop._id, experience: { primaryTrade: 'Plumbing', years: 3 }, rates: { dailyFloorRate: 100, hourlyRate: 50 }, documents: { addressProof: { expiresAt: new Date(Date.now() + 86400000) } } });
  http.listen(0, '127.0.0.1'); await once(http, 'listening');
  const url = `http://127.0.0.1:${http.address().port}`;
  const connect = async user => {
    const socket = client(url, { auth: { token: AuthService.generateToken(user) }, forceNew: true, reconnection: false });
    sockets.push(socket);
    await once(socket, 'connect', { signal: AbortSignal.timeout(5000) });
    return socket;
  };
  const customerSocket = await connect(customer);
  const strangerSocket = await connect(stranger);
  const customerSecond = await connect(customer);
  let strangerEvents = 0;
  strangerSocket.on('notification:new', () => strangerEvents++);
  strangerSocket.emit('join', `notifications:USER:${customer._id}`);
  const received = once(customerSocket, 'notification:new', { signal: AbortSignal.timeout(5000) });
  const notification = await notify({ recipientId: customer._id, recipientRole: 'USER', type: 'PAYMENT_CONFIRMED', title: 'Payment confirmed', message: 'Test receipt', eventKey: 'receipt-1' });
  const [event] = await received;
  check(event._id === String(notification._id), 'Persisted notification delivered instantly to authenticated recipient');
  await notify({ recipientId: customer._id, recipientRole: 'USER', type: 'PAYMENT_CONFIRMED', title: 'Payment confirmed', message: 'Test receipt', eventKey: 'receipt-1' });
  check(await Notification.countDocuments({ eventKey: 'receipt-1' }) === 1, 'Event keys deduplicate repeated delivery');
  const request = async (user, path, method = 'GET', body) => {
    const response = await fetch(`${url}/api/notifications${path}`, { method, headers: { Authorization: `Bearer ${AuthService.generateToken(user)}`, 'Content-Type': 'application/json' }, ...(body && { body: JSON.stringify(body) }) });
    return { status: response.status, body: await response.json() };
  };
  check((await request(customer, '?filter=Payment')).body.data.total === 1, 'Category filtering reads MongoDB');
  check((await request(stranger, '')).body.data.total === 0, 'List excludes other accounts');
  check((await request(stranger, `/${notification._id}/read`, 'PATCH')).status === 404, 'Cannot mark another account notification read');
  check((await request(customer, '?filter=Invalid')).status === 400, 'Invalid filters are rejected');
  check((await request(customer, '?page=-1')).status === 400, 'Invalid pagination is rejected');
  const changed = once(customerSecond, 'notifications:changed', { signal: AbortSignal.timeout(5000) });
  await request(customer, `/${notification._id}/read`, 'PATCH'); await changed;
  check((await request(customer, '/unread-count')).body.data.unreadCount === 0, 'Read actions sync tabs and unread count');
  const booking = await BookingService.createBooking(customer._id, { serviceName: 'Plumbing', trade: 'Plumbing', workerId: worker._id, cooperativeId: coop._id, location: { serviceAddress: { street: 'Test Street', city: 'Test District' }, coordinates: [73, 18] }, scheduledTime: { start: new Date(Date.now() + 86400000) }, floorRate: 100, totalAmount: 100 });
  check(await Notification.exists({ recipientId: workerUser._id, type: 'NEW_BOOKING' }), 'Worker profile resolves to login account');
  check(await Notification.exists({ recipientId: manager._id, type: 'NEW_BOOKING' }), 'Cooperative resolves to manager login account');
  const member = await CooperativeService.addMember(coop._id, { phone: workerUser.phone });
  check(String(member._id) === String(worker._id), 'Cooperative membership persists real worker IDs');
  await BookingService.updateBookingStatus(booking._id, undefined, customer._id, 'USER', { scheduledTime: { start: new Date(Date.now() + 172800000) } });
  check(await Notification.exists({ recipientId: workerUser._id, type: 'RESCHEDULED' }), 'Rescheduling notifies assigned worker');
  const rejectedBooking = await Booking.create({ customer: customer._id, worker: worker._id, cooperative: coop._id, serviceName: 'Test', trade: 'Plumbing', status: 'ASSIGNED', price: { floorRateAmount: 100, totalAmount: 100 }, scheduledTime: { start: new Date(Date.now() + 86400000) } });
  await BookingService.rejectBooking(rejectedBooking._id, workerUser._id, 'Unavailable');
  check(await Notification.exists({ recipientId: manager._id, type: 'REJECTED', relatedBooking: rejectedBooking._id }), 'Rejected assignment notifies cooperative');
  await BookingService.updateBookingStatus(rejectedBooking._id, 'CANCELLED', admin._id, 'ADMIN');
  check(await Notification.exists({ recipientId: workerUser._id, type: 'CANCELLED', relatedBooking: rejectedBooking._id }), 'Cancellation notifies assigned worker');
  await BookingService.acceptBooking(booking._id, workerUser._id);
  check(await Notification.exists({ recipientId: manager._id, type: 'ACCEPTED' }), 'Worker acceptance notifies cooperative');
  await BookingService.updateBookingStatus(booking._id, 'ON_THE_WAY', workerUser._id, 'WORKER');
  await BookingService.updateBookingStatus(booking._id, 'ARRIVED', workerUser._id, 'WORKER');
  check(await Notification.exists({ recipientId: customer._id, type: 'ARRIVED' }), 'Arrival notifies customer');
  await assert.rejects(issueWorkOtp(booking._id, 'start', customer._id, 'USER'), { statusCode: 409 });
  const payment = await Payment.create({ booking: booking._id, customer: customer._id, razorpayOrderId: 'order_notification_test', razorpayPaymentId: 'pay_notification_test', gatewayKeyId: 'rzp_test_integration', verifiedVia: 'gateway', amount: Math.round(booking.price.totalAmount * 100), currency: 'INR', status: 'escrow_locked', paidAt: new Date() });
  await Booking.updateOne({ _id: booking._id }, { $set: { paymentStatus: 'escrow_locked', paymentRecord: payment._id, 'paymentProvider.transactionId': payment.razorpayPaymentId, 'paymentProvider.confirmedAt': payment.paidAt } });
  const start = await issueWorkOtp(booking._id, 'start', customer._id, 'USER');
  check(!(JSON.stringify(await Notification.find({}).lean())).includes(start.code), 'OTP code never enters notifications');
  const beforeWrong = await Notification.countDocuments();
  await assert.rejects(verifyWorkOtp(booking._id, 'start', start.code === '000000' ? '111111' : '000000', workerUser._id, 'WORKER'));
  check(await Notification.countDocuments() === beforeWrong, 'Failed OTP generates no success notification');
  await verifyWorkOtp(booking._id, 'start', start.code, workerUser._id, 'WORKER');
  const end = await issueWorkOtp(booking._id, 'end', customer._id, 'USER');
  await verifyWorkOtp(booking._id, 'end', end.code, workerUser._id, 'WORKER');
  check(await Notification.exists({ recipientId: workerUser._id, type: 'PAYMENT_RELEASED' }), 'Actual held-escrow release notifies worker');
  check(await Notification.exists({ recipientId: customer._id, type: 'PAYMENT_RELEASED' }), 'Payment release notifies customer');
  check(await Notification.exists({ recipientId: manager._id, type: 'SETTLEMENT_COMPLETED' }), 'Settlement notification reaches the booking cooperative');
  check(await Notification.exists({ recipientId: customer._id, type: 'RATING_REMINDER' }), 'Completion creates rating reminder');
  const completedCount = await Notification.countDocuments({ type: 'COMPLETED' });
  await assert.rejects(verifyWorkOtp(booking._id, 'end', end.code, workerUser._id, 'WORKER'));
  check(await Notification.countDocuments({ type: 'COMPLETED' }) === completedCount, 'Replayed OTP does not duplicate completion');
  await AdminService.reviewVerification({ applicantType: 'worker', applicantId: worker._id, status: 'verified' });
  check(await Notification.exists({ recipientId: workerUser._id, type: 'VERIFICATION_APPROVED' }), 'Profile approval notifies worker account');
  await AdminService.reviewVerification({ applicantType: 'cooperative', applicantId: coop._id, status: 'rejected' });
  check(await Notification.exists({ recipientId: manager._id, type: 'VERIFICATION_REJECTED' }), 'Cooperative rejection notifies manager');
  await scanNotificationReminders(); await scanNotificationReminders();
  check(await Notification.countDocuments({ type: 'DOCUMENT_EXPIRY', recipientId: workerUser._id }) === 1, 'Expiry reminder is persisted and deduplicated');
  const pending = await Booking.create({ customer: customer._id, serviceName: 'Plumbing', trade: 'Plumbing', status: 'PENDING', price: { floorRateAmount: 100, totalAmount: 100 }, scheduledTime: { start: new Date() }, location: { type: 'Point', coordinates: [73, 18], serviceAddress: { city: 'Unserved District' } } });
  process.env.NOTIFICATION_DEMAND_THRESHOLD = '1';
  await scanNotificationReminders();
  check(await Notification.exists({ recipientId: admin._id, type: 'HIGH_DEMAND' }), 'High-demand scan notifies admins');
  check(await Notification.exists({ recipientId: admin._id, type: 'WORKER_SHORTAGE' }), 'Worker shortage scan notifies admins');
  await bookingNotification(pending, 'DISPUTED');
  check(await Notification.exists({ recipientId: admin._id, type: 'COMPLAINT_SUBMITTED' }), 'Booking dispute creates admin complaint notification');
  await request(customer, '/read-all', 'PATCH');
  check((await request(customer, '?filter=Unread')).body.data.total === 0, 'Mark all read updates the full recipient inbox');
  check(await Notification.countDocuments({ recipientId: workerUser._id, isRead: false }) > 0, 'Mark all read preserves other accounts');
  check(strangerEvents === 0, 'Client room spoofing cannot leak another account notifications');
  const bad = client(url, { auth: { token: 'invalid' }, forceNew: true, reconnection: false }); sockets.push(bad);
  const [failure] = await once(bad, 'connect_error', { signal: AbortSignal.timeout(5000) });
  check(failure.message === 'Authentication required', 'Invalid socket token rejected');
  const inactive = await User.create({ name: 'Inactive', phone: '9900000009', role: 'USER', password: 'test-password', isActive: false });
  const blocked = client(url, { auth: { token: AuthService.generateToken(inactive) }, forceNew: true, reconnection: false }); sockets.push(blocked);
  const [inactiveError] = await once(blocked, 'connect_error', { signal: AbortSignal.timeout(5000) });
  check(inactiveError.message === 'Authentication required', 'Inactive account cannot open a notification socket');
  customerSocket.disconnect();
  await notify({ recipientId: stranger._id, recipientRole: 'USER', type: 'BOOKING_SUBMITTED', title: 'Saved offline', message: 'Persisted' });
  check((await request(stranger, '')).body.data.total === 1, 'REST inbox recovers persisted notifications without a socket');
  const originalCreate = Notification.create;
  Notification.create = async () => { throw new Error('simulated unavailable database'); };
  await safelyNotify(() => notify({ recipientId: customer._id, recipientRole: 'USER', type: 'BOOKING_SUBMITTED', title: 'Test', message: 'Test' }));
  Notification.create = originalCreate;
  check(true, 'Notification failure is isolated from committed business operations');
  console.log(`Notifications: ${passed} checks passed`);
} finally {
  sockets.forEach(socket => socket.disconnect());
  await new Promise(resolve => io.close(resolve));
  assert.ok(mongoose.connection.name.startsWith('shramsetu_notifications_test_'));
  await mongoose.connection.dropDatabase();
  await mongoose.disconnect();
}
